### PR TITLE
[IMP] Add support for Odoo 11 + Drop support for Python 3.2 and 3.3

### PR DESCRIPTION
**Pull request by sebalix**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Travis is red in 11.0 builds. Maybe it's the combination with Python 2.x?

**Comment by sebalix** [comment]
There are several tests which fail on 11.0:
- reports (`ir.actions.report.xml` removed)
- exec_workflow (workflow removed too)
- fields.Reference (need to find an existing field to test in the standard)
- maybe Python 2.7 indeed, it should be nicer to execute Odoo on 3.5 (while testing OdooRPC on all other Python versions), don't know if it can be done easily on Travis

**Comment by pedrobaeza** [comment]
Can we disable that features?

Indeed, we want to add Docker support to OCA Travis infrastructure. See https://github.com/OCA/maintainer-quality-tools/pull/477 and https://github.com/OCA/runbot-addons/issues/144

**Comment by sebalix** [comment]
Reports features have to be adapted, and `exec_workflow` tests should be disabled against v11.

**Comment by hugovk** [comment]
By the way, here's the pip installs for odoorpc from PyPI for the last month -- no 3.2 or 3.3!
```
$ pypinfo --percent --pip odoorpc pyversion
python_version percent download_count
-------------- ------- --------------
2.7              85.1%          1,270
3.5               7.7%            115
3.6               6.4%             95
3.4               0.7%             11
2.6               0.1%              1

```

**Comment by pedrobaeza** [comment]
You can rebase here now.

**Comment by sebalix** [comment]
It takes me some time to make OdooRPC compatible with Odoo 11.0 (and keep the compatibility 10, 9 and 8).
One of the headache was that the report service has been removed in favor of the new method `render(...)` on `ir.actions.report` model. I could download any document but the PDF ones was just empty/blank, and I just discovered that the `bytes` object was encoded as `latin1/iso-8859-1/cp1252` (depending of the locale environment) in the report JSON document returned by the JSON-RPC layer (https://github.com/odoo/odoo/blob/11.0/odoo/loglevels.py#L81)...
Now I need to make this compatible with all Odoo releases + Python2/3.

**Comment by pedrobaeza** [comment]
You can let the Report support for later if you want.

**Comment by sebalix** [comment]
@pedrobaeza : I think we are finally OK with this PR, waiting for CI tests to pass...

**Comment by sebalix** [comment]
@pedrobaeza ready to merge

**Comment by sebalix** [comment]
No not yet, I have to make a new PR for the release (bump version + tag).

**Comment by pedrobaeza** [comment]
OK, you can check what we do in openupgradelib: https://github.com/OCA/openupgradelib/blob/master/.travis.yml#L36-L42

**Comment by sebalix** [comment]
Thank you, I will have a look on this. Also, as this project uses `git-flow` and releases are made from the ``master`` branch, I think that a new PR on ``master`` (with tag) is required even with the Travis auto-publish configuration.

Regarding the PyPI deployement, I should transfer the ownership to `OCA` user, don't you think?

**Comment by pedrobaeza** [comment]
Yeah, it would be desirable.

**Comment by sebalix** [comment]
- `OCA` PyPI user own the project now
- Commits squashed
- Travis configuration for auto-deployement added (copy-paste from `openupgradelib`)

I think we can merge this one!

**Comment by pedrobaeza** [comment]
Great! Thanks again.

Merging this although OCA review process involves at least 2 reviewers, but I consider that this should be already ready as a base for continuing from this with usual review flow.

**Comment by pedrobaeza** [comment]
Should we maintain both develop/master branches? I prefer to only have `master` one (which should be now the develop one), and remove the other. The rest of changes will be included through PRs.

**Comment by sebalix** [comment]
Well, thinking about it you may be right, the `git-flow` development is not really needed, and contributors don't target the `develop` branch automatically.
Go for `master` only, it'll make things simpler. For now, I'll push the next release directly myself.

**Comment by sebalix** [comment]
I updated ``master`` (+ tag 0.6.1) and ``develop``, I'm waiting Travis to push the release on PyPI (I'll upload the documentation manually right after).

**Comment by pedrobaeza** [comment]
OK, thanks. Let me know when you have it.

**Pull request merged**
